# Here are the scripts to get familiar with Numpy

In [1]:
import numpy as np
data1 = [1,2,3,4,5]
array1 = np.array(data1)
array1

array([1, 2, 3, 4, 5])

 - Numpy是Python的第三方工具包，使用的时候用 “import” 关键字导入。同时我们为了后续方便使用，给它起一个缩写名称“np”，相当于外号。
 - data1是一个变量名， 我们给它赋值为一个list。
 - 使用Numpy的array函数，我们把list 转换成 Numpy中的数组。
 - 打印array1 中的元素

In [2]:
data2 = [[1,3,4],[2,5,6]]
array2 = np.array(data2)
array2

array([[1, 3, 4],
       [2, 5, 6]])

- data2 是一个元素嵌套的列表
- 使用 Numpy的array 函数把data2 转换成Numpy中的多维数组，也就是我们说的Matrix 矩阵。

In [3]:
array2.dtype

dtype('int32')

- 使用数组对象的方法“dtype”，查询数组内部数据类型。使用方法是“对象（变量）名称.方法名”

In [4]:
array1.astype('str')

array(['1', '2', '3', '4', '5'], dtype='<U11')

- 使用数组对象内置函数可以把数组的元素数据类型转换成其他格式。
- 本例中，我们把 “整型” 转换成 “字符型”。

In [5]:
array1 + 1

array([2, 3, 4, 5, 6])

对数组内每个元素+1 运算

In [6]:
array1 * array1

array([ 1,  4,  9, 16, 25])

数组和数组，进行乘法运算

In [7]:
array1 * 2

array([ 2,  4,  6,  8, 10])

对数组进行乘法运算

In [8]:
array1

array([1, 2, 3, 4, 5])

In [9]:
array1[3]

4

通过方括号+数字，访问数组内的元素

In [10]:
array1[-2:]

array([4, 5])

负数cursor的含义是从数组尾部倒数位数，冒号相当于汉语的“至”，冒号后没有给出截止范围，则表示打印至末尾。

In [11]:
array1[1] = 0
array1

array([1, 0, 3, 4, 5])

对数组中某个元素重新赋值

In [12]:
array2

array([[1, 3, 4],
       [2, 5, 6]])

In [13]:
array2[0]

array([1, 3, 4])

对于二位数组/矩阵，第一个元素是二维矩阵第一行所有元素

In [14]:
array2[0][1]

3

如果要访问数组第一行第二个数据，我们采用下标形式为“[0][1]”

以上只是基本操作，除此以外，还有reshape， T转置，ufunc， sort 等函数，功能强大。具体使用方法可以查阅相关文档。
https://www.numpy.org/devdocs/reference/arrays.ndarray.html